
services:
  nginx:
    image: nginx:latest
    container_name: IsticharaNginxContainer
    ports:
      - "8080:80"
    volumes:
<<<<<<< HEAD
      - ./src:/var/www/html 
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
=======
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
>>>>>>> main
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: IsticharaPhpContainer
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t && pgrep php-fpm"]
      interval: 5s
      retries: 5
      start_period: 5s
<<<<<<< HEAD
    env_file:
      - .env
=======
>>>>>>> main

  mysql:
    image: mysql:8.0
    container_name: IsticharamysqlContainer
    restart: always
    ports:
      - "3308:3306"
    environment:
<<<<<<< HEAD
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-camus}
      MYSQL_DATABASE: ${DB_DATABASE:-IsticharaDB}
=======
      MYSQL_ROOT_PASSWORD: camus
      MYSQL_DATABASE: IsticharaDB
>>>>>>> main
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Isticharaphpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  db-data:
  


  