version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: IsticharaNginxContainer
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: IsticharaPhpContainer
    volumes:
      - ./src:/var/www/html
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=IsticharaDB
      - DB_USERNAME=root
      - DB_PASSWORD=camus

  mysql:
    image: mysql:8.0
    container_name: IsticharamysqlContainer
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: camus
      MYSQL_DATABASE: IsticharaDB
      MYSQL_PASSWORD: camus
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Isticharaphpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 256M
    depends_on:
      - mysql

volumes:
  db-data:
